LibraryWebApp/Models/Publisher.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace LibraryWebApp.Models
{
    public class Publisher
    {
        [Required]
        [Key]
        public int Id { get; set; }

        [Required]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Required]
        public string Country { get; set; }

        [Required]
        public string City { get; set; }

        [Required]
        public string Address { get; set; }

        [Required]
        [Phone]
        [Display(Name = "Phone")]
        public string PhoneNumber { get; set; }

        public virtual ICollection<Book> Books { get; set; }

        public Publisher()
        {
            Books = new List<Book>();
        }
    }
}

LibraryWebApp/Controllers/PublishersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LibraryWebApp.Models;
using LibraryWebApp.Models.ViewModels;


namespace LibraryWebApp.Controllers
{
    public class PublishersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Publishers/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id, string returnUrl)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var publisher = db.Publishers.Include(a => a.Books).FirstOrDefault(a => a.Id == id);

            if (publisher == null)
            {
                return HttpNotFound();
            }

            var booksByPublisher = publisher.Books.ToList();


            var model = new PublisherDetailsViewModel()
            {
                Publisher = publisher,
                BooksByPublisher = booksByPublisher
            };

            ViewBag.ReturnUrl = returnUrl;
            return View(model);
        }

        // GET: Publishers/Create
        [Authorize(Roles = "Admin, Staff")]
        public ActionResult Create(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        // POST: Publishers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Staff")]
        public ActionResult Create([Bind(Include = "Id,Name,Country,City,Address,PhoneNumber")] Publisher publisher, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                db.Publishers.Add(publisher);
                db.SaveChanges();
                return RedirectToLocal(returnUrl);
            }

            ViewBag.ReturnUrl = returnUrl;
            return View(publisher);
        }

        // GET: Publishers/Edit/5
        [Authorize(Roles = "Admin, Staff")]
        public ActionResult Edit(int? id, string returnUrl)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Publisher publisher = db.Publishers.Find(id);
            if (publisher == null)
                return HttpNotFound();


            ViewBag.ReturnUrl = returnUrl;
            return View(publisher);
        }

        // POST: Publishers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Staff")]
        public ActionResult Edit([Bind(Include = "Id,Name,Country,City,Address,PhoneNumber")] Publisher publisher, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                db.Entry(publisher).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToLocal(returnUrl);
            }

            ViewBag.ReturnUrl = returnUrl;
            return View(publisher);
        }

        // GET: Publishers/Delete/5
        [Authorize(Roles = Roles.Admin)]
        public ActionResult Delete(int? id, string returnUrl)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Publisher publisher = db.Publishers.Find(id);
            if (publisher == null)
                return HttpNotFound();
            
            db.Publishers.Remove(publisher);
            db.SaveChanges();
            return RedirectToLocal(returnUrl);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }

            return RedirectToAction("Index", "Books");
        }
    }
}

LibraryWebApp/Views/Publishers/Create.cshtml
@model LibraryWebApp.Models.Publisher

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="container" class="container">
    <div class="row bg-primary">
        <div class="col-sm-12 text-center">
            <h3>Create a new Publisher</h3>
        </div>
    </div>

    <br />

    <div class="row">
        <div class="col-sm-8">

            @using (Html.BeginForm("Create", "Publishers", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger small" })
                    <div class="form-group required">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2", style = "cursor: pointer;" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger alert-danger small" })
                        </div>
                    </div>

                    <div class="form-group required">
                        @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2", style = "cursor: pointer;" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger alert-danger small" })
                        </div>
                    </div>

                    <div class="form-group required">
                        @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2", style = "cursor: pointer;" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger alert-danger small" })
                        </div>
                    </div>

                    <div class="form-group required">
                        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2", style = "cursor: pointer;" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger alert-danger small" })
                        </div>
                    </div>

                    <div class="form-group required">
                        @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2", style = "cursor: pointer;" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger alert-danger small" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@section styles
{
    <style>
        .form-group.required .control-label:after {
            content: "*";
            font-size: 16px;
            color: red;
        }
    </style>
}

LibraryWebApp/Views/Publishers/Delete.cshtml
@model LibraryWebApp.Models.Publisher

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Publisher</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LibraryWebApp/Views/Publishers/Details.cshtml
@model LibraryWebApp.Models.ViewModels.PublisherDetailsViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="container" class="container">
    <div class="row bg-primary">
        <div class="col-sm-12 text-center">
            <h3>@ViewBag.Title for @Model.Publisher.Name</h3>
        </div>
    </div>

    <br />
    
    <div class="row">
        <div class="col-xs-12 col-md-12 col-sm-12 col-lg-12">
            <p>@Model.Publisher.Name is located in <strong>@Model.Publisher.Country</strong> near <strong>@Model.Publisher.City</strong></p>
            <p>You can contact them on <strong>@Model.Publisher.PhoneNumber</strong> or visit their studio which can be found on <strong>@Model.Publisher.Address</strong></p>
        </div>
    </div>

    <br />
    <div class="row">

        <div class="col-xs-12 col-md-12 col-sm-12 col-lg-12 text-center">
            <h4 style="color: firebrick;">Short history for @Model.Publisher.Name</h4>
        </div>
    </div>

    <div class="row">

        <div class="col-xs-12 col-md-12 col-sm-12 col-lg-12 text-left">
            <p>
                Praesent sit amet rhoncus neque, ut maximus urna. Nam fermentum elit ante. Mauris laoreet nisi ligula, 
                at dictum nibh lobortis id. In scelerisque congue eros, vel pellentesque nisi ullamcorper in. Quisque 
                pharetra mauris non ultricies dignissim. Curabitur odio arcu, tristique a egestas vitae, iaculis sit 
                amet orci. Aenean eget orci posuere nulla interdum suscipit. Donec pharetra purus ut tellus venenatis 
                laoreet. Donec pellentesque massa sit amet urna commodo, eu ullamcorper purus luctus. Sed orci ligula, 
                finibus sit amet congue a, suscipit eu lorem. Nunc elementum pretium felis et lacinia. Aliquam erat 
                volutpat.
            </p>
            <hr />
            <p>
                Vestibulum sollicitudin purus eget quam consequat, lobortis venenatis nisl ullamcorper. Donec ac leo 
                molestie, dapibus sapien id, laoreet dui. Vestibulum ornare consectetur dui ut venenatis. Nulla quis 
                feugiat odio. In orci dui, dapibus quis ornare id, sodales in justo. Pellentesque non metus vitae sapien 
                dapibus hendrerit ut tristique mauris. Interdum et malesuada fames ac ante ipsum primis in faucibus. 
                Pellentesque quis dictum urna. Donec id posuere dui, in iaculis nibh. Morbi vitae ultrices magna. Morbi 
                vel nibh ullamcorper, feugiat sem eget, consectetur tortor. Etiam sed lectus orci. Pellentesque eget 
                dolor varius, tempor felis ac, luctus nunc. Nullam vestibulum nulla elit, sed venenatis diam vestibulum 
                at. Curabitur in massa ante.
            </p>
        </div>
    </div>

    <br />

    <div class="row">
        <div class="col-xs-1 col-md-2 col-lg-2 text-left">
            @if (User.IsInRole("Admin") || User.IsInRole("Staff"))
            {
                @Html.ActionLink("Edit", "Edit", "Publishers", new { id = Model.Publisher.Id, ReturnUrl = Html.Encode($"/Publishers/Details/{Model.Publisher.Id}") }, new { @class = "btn btn-warning" })
            }
            @if (User.IsInRole("Admin"))
            {
                @Html.ActionLink("Delete", "Delete", "Publishers", new { id = Model.Publisher.Id, ReturnUrl = ViewBag.ReturnUrl }, new { @class = "btn btn-danger js-delete" })
            }
        </div>
    </div>
    
    @if (Model.BooksByPublisher.Count != 0)
    {
        <div class="row">
            <div class="col-xs-12 col-md-12 col-sm-12 col-lg-12 text-center">
                <h4 style="color: firebrick">Books published by @Model.Publisher.Name</h4>
            </div>
        </div>

        <div id="genreCarousel" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                @for (int i = 0; i < Model.BooksByPublisher.Count; ++i)
                {
                    if (i == 0)
                    {
                        <li data-target="#genreCarousel" data-slide-to="@i" class="active"></li>
                    }
                    else
                    {
                        <li data-target="#genreCarousel" data-slide-to="@i"></li>
                    }
                }
            </ol>

            <div class="carousel-inner" role="listbox" style="background-color: gray">
                @for (int i = 0; i < Model.BooksByPublisher.Count; ++i)
                {
                    if (i == 0)
                    {
                        <div class="item active" style="background-color: gray">
                            <a href="/Books/Details/@Model.BooksByPublisher[i].Id?ReturnUrl=@(Html.Encode($"/Publishers/Details/{Model.Publisher.Id}"))">
                                <img src="@Model.BooksByPublisher[i].CoverURL" class="img-responsive img-thumbnail center-block" style="height: 280px"/>
                            </a>
                        </div>
                    }
                    else
                    {
                        <div class="item" style="background-color: gray">
                            <a href="/Books/Details/@Model.BooksByPublisher[i].Id?ReturnUrl=@(Html.Encode($"/Publishers/Details/{Model.Publisher.Id}"))">
                                <img src="@Model.BooksByPublisher[i].CoverURL" class="img-responsive img-thumbnail center-block" style="height: 280px"/>
                            </a>
                        </div>
                    }
                }

            </div>
            <a class="left carousel-control" href="#genreCarousel" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#genreCarousel" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    }
    else
    {
        <h4 class="alert-danger"><span class="text-danger">This publisher does not have books yet</span></h4>
    }

    <br/>

    <div class="row">
        <div class="col-sm-12 col-md-12 col-lg-12 text-right">
            @if (ViewBag.ReturnUrl == null)
            {
                @Html.ActionLink("Back to list", "Index", "Books", new { }, new { @class = "btn btn-primary" })
            }
            else
            {
                <a href="@ViewBag.ReturnUrl" class="btn btn-primary">Back to list</a>
            }
        </div>
    </div>

    <br />
</div>

<div id="dialog-delete">
    <p class="alert alert-danger text-danger">
        <span class="glyphicon glyphicon-alert"></span>
        <span>Are you sure you want to delete this item?</span>
    </p>
</div>

@section styles
{
    <link rel="stylesheet" type="text/css" href="@Href("~/Content/jquery-ui.css")" />
}

@section scripts{
    <script type="text/javascript" src="@Href("~/Scripts/jquery-ui.js")"></script>

    <script type="text/javascript">
        var button;

        $(document).ready(function() {
            var dialogDelete = $("#dialog-delete").dialog({
                resizable: false,
                draggable: false,
                autoOpen: false,
                width: 400,
                modal: true,
                title: "Delete confirmation",
                buttons: {
                    Yes: function () {
                        var url = button.attr("href");
                        window.location = url;
                        dialogDelete.dialog("close");
                    
                    },
                    No: function () {
                        dialogDelete.dialog("close");
                    }
                }
            });

            $("body").on("click", "a.js-delete", function (event) {
                event.preventDefault();
                button = $(this);
                dialogDelete.dialog("open");
            });

            $('.carousel').carousel({
                visible: 5,
                animation: 5000,
                pause: "hover",
                scroll: 1,
                wrap: "circular"
            });
        });
    </script>
}

LibraryWebApp/Views/Publishers/Edit.cshtml
@model LibraryWebApp.Models.Publisher

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="container" class="container">
    <div class="row bg-primary">
        <div class="col-sm-12 text-center">
            <h3>Edit</h3>
        </div>
    </div>

    <br />

    <div class="row">
        <div class="col-sm-8">

            @using (Html.BeginForm("Edit", "Publishers", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger small" })
                    @Html.HiddenFor(model => model.Id)

                    <div class="form-group required">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2", style = "cursor: pointer;" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger alert-danger small" })
                        </div>
                    </div>

                    <div class="form-group required">
                        @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label col-md-2", style = "cursor: pointer;" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger alert-danger small" })
                        </div>
                    </div>

                    <div class="form-group required">
                        @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2", style = "cursor: pointer;" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger alert-danger small" })
                        </div>
                    </div>

                    <div class="form-group required">
                        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2", style = "cursor: pointer;" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger alert-danger small" })
                        </div>
                    </div>

                    <div class="form-group required">
                        @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2", style = "cursor: pointer;" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger alert-danger small" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@section styles
{
    <style>
        .form-group.required .control-label:after {
            content: "*";
            font-size: 16px;
            color: red;
        }
    </style>
}