LibraryWebApp/Models/Book.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LibraryWebApp.Models
{
    public class Book
    {
        [Required]
        [Key]
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "The Pages field must be greater than zero")]
        public int Pages { get; set; }

        [Required]
        [Range(0, int.MaxValue, ErrorMessage = "The Quantity field must be non-negative number")]
        public int Quantity { get; set; }

        public Genre Genre { get; set; }

        [Required]
        [Range(0, 100000.00, ErrorMessage = "The Price field must be non-negative number")]
        public decimal Price { get; set; }

        [Display(Name = "Cover URL")]
        public string CoverURL { get; set; }

        [Required]
        [Display(Name = "Publish Place")]
        public string PublishPlace { get; set; }

        [Required]
        [Column(TypeName = "datetime2")]
        [Display(Name = "Publish Date")]
        public DateTime PublishDate { get; set; }

        public virtual ICollection<Author> Authors { get; set; }

        public virtual ICollection<Publisher> Publishers { get; set; }

        public virtual ICollection<Review> Reviews { get; set; }


        public Book()
        {
            Authors = new List<Author>();
            Publishers = new List<Publisher>();
            Reviews = new List<Review>();
            Pages = 1;
        }
    }
}

LibraryWebApp/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.WebPages;
using LibraryWebApp.Models;
using LibraryWebApp.Models.ViewModels;
using PagedList;
using LibraryWebApp.Models.Dto;

namespace LibraryWebApp.Controllers
{
    public class BooksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        
        // GET: Books
        [AllowAnonymous]
        public ActionResult Index(int? page, string orderBy)
        {
            var pageNumber = page ?? 1;
            var pageSize = 16;

            var books = db.Books.Include(m => m.Authors);

            IOrderedQueryable<Book> model;
            switch (orderBy)
            {
                case "price-asc":
                    model = books.OrderBy(b => b.Price);
                    break;
                case "price-desc":
                    model = books.OrderByDescending(b => b.Price);
                    break;
                case "publish-asc":
                    model = books.OrderBy(b => b.PublishDate);
                    break;
                case "publish-desc":
                    model = books.OrderByDescending(b => b.PublishDate);
                    break;
                case "title-asc":
                    model = books.OrderBy(b => b.Title);
                    break;
                case "title-desc":
                    model = books.OrderByDescending(b => b.Title);
                    break;
                case "quantity-asc":
                    model = books.OrderBy(b => b.Quantity);
                    break;
                case "quantity-desc":
                    model = books.OrderByDescending(b => b.Quantity);
                    break;
                default:
                    model = books.OrderBy(b => b.Title);
                    break;
            }

            ViewBag.UserRole = User.IsInRole(Roles.Admin) ? "Admin" :
                User.IsInRole(Roles.Staff) ? "Staff" :
                User.IsInRole(Roles.Member) ? "Member" :
                User.IsInRole(Roles.User) ? "User" : "";

            ViewBag.OrderBy = orderBy;

            return View(model.ToPagedList(pageNumber, pageSize));
        }
        
        // GET: Books/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id, string returnUrl)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Book book = db.Books.Include(b => b.Genre).FirstOrDefault(b => b.Id == id);

            if (book == null)
            {
                return HttpNotFound();
            }

            var booksByGenre = db.Books.Include(b => b.Genre).Where(b => b.Genre.Name == book.Genre.Name).ToList();
            booksByGenre.Remove(book);

            var reviewsForBook = book.Reviews.OrderByDescending(item => item.ReviewDate).ToList();

            var model = new BookDetailsViewModel()
            {
                Book = book,
                BooksByGenre = booksByGenre,
                ReviewsForBook = reviewsForBook
            };

            ViewBag.ReturnUrl = returnUrl;
            return View(model);
        }

        // GET: Books/Create
        [Authorize(Roles = "Admin, Staff")]
        public ActionResult Create(string returnUrl)
        {
            var model = new AddAuthorToBookModel()
            {
                Book = new Book(),
                Authors = (db.Authors.ToList()),
                SelectedAuthor = -1,
                Publishers = (db.Publishers.ToList()),
                SelectedPublisher = -1,
                Genres = (db.Genres.ToList()),
                SelectedGenre = -1
            };

            ViewBag.ReturnUrl = returnUrl;
            return View(model);
        }

        // POST: Books/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Staff")]
        public ActionResult Create(AddAuthorToBookModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                var book = new Book()
                {
                    Title = model.Book.Title,
                    Pages = model.Book.Pages,
                    Quantity = model.Book.Quantity,
                    CoverURL = model.Book.CoverURL,
                    PublishPlace = model.Book.PublishPlace,
                    PublishDate = model.Book.PublishDate,
                    Price = model.Book.Price,
                };
                var author = db.Authors.Find(model.SelectedAuthor);
                if (author == null)
                {
                    model = new AddAuthorToBookModel()
                    {
                        Book = new Book(),
                        Authors = (db.Authors.ToList()),
                        SelectedAuthor = -1,
                        Publishers = (db.Publishers.ToList()),
                        SelectedPublisher = -1,
                        Genres = (db.Genres.ToList()),
                        SelectedGenre = -1
                    };

                    ViewBag.ReturnUrl = returnUrl;
                    ViewBag.ErrorAuthor = "Author does not exists!";
                    return View(model);
                }
                book.Authors.Add(db.Authors.Find(model.SelectedAuthor));

                var publisher = db.Publishers.Find(model.SelectedPublisher);
                if (publisher == null)
                {
                    model = new AddAuthorToBookModel()
                    {
                        Book = new Book(),
                        Authors = (db.Authors.ToList()),
                        SelectedAuthor = -1,
                        Publishers = (db.Publishers.ToList()),
                        SelectedPublisher = -1,
                        Genres = (db.Genres.ToList()),
                        SelectedGenre = -1
                    };

                    ViewBag.ReturnUrl = returnUrl;
                    ViewBag.ErrorPublisher = "Publisher does not exists!";
                    return View(model);
                }
                book.Publishers.Add(db.Publishers.Find(model.SelectedPublisher));

                var genre = db.Genres.Find(model.SelectedGenre);
                if (genre == null)
                {
                    model = new AddAuthorToBookModel()
                    {
                        Book = new Book(),
                        Authors = (db.Authors.ToList()),
                        SelectedAuthor = -1,
                        Publishers = (db.Publishers.ToList()),
                        SelectedPublisher = -1,
                        Genres = (db.Genres.ToList()),
                        SelectedGenre = -1
                    };

                    ViewBag.ReturnUrl = returnUrl;
                    ViewBag.ErrorGenre = "Genre does not exists!";
                    return View(model);
                }
                book.Genre = genre;

                db.Books.Add(book);
                db.SaveChanges();

                return RedirectToLocal(returnUrl);
            }

            model = new AddAuthorToBookModel()
            {
                Book = new Book(),
                Authors = (db.Authors.ToList()),
                SelectedAuthor = -1,
                Publishers = (db.Publishers.ToList()),
                SelectedPublisher = -1,
                Genres = (db.Genres.ToList()),
                SelectedGenre = -1
            };

            ViewBag.ReturnUrl = returnUrl;
            return View(model);
        }
        
        // GET: Books/Edit/5
        [Authorize(Roles = "Admin, Staff")]
        public ActionResult Edit(int? id, string returnUrl)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }

            var model = new AddAuthorToBookModel()
            {
                Book = book,
                Authors = db.Authors.ToList(),
                SelectedAuthor = -1,
                Publishers = db.Publishers.ToList(),
                SelectedPublisher = -1,
                Genres = db.Genres.ToList(),
                SelectedGenre = -1,
            };

            ViewBag.ReturnUrl = returnUrl;
            return View(model);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Staff")]
        public ActionResult Edit(AddAuthorToBookModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                var book = db.Books.Find(model.Book.Id);
                if (book == null)
                    return HttpNotFound();

                book.Title = model.Book.Title;
                book.Pages = model.Book.Pages;
                book.Quantity = model.Book.Quantity;
                book.CoverURL = model.Book.CoverURL;
                book.PublishPlace = model.Book.PublishPlace;
                book.PublishDate = model.Book.PublishDate;
                book.Price = model.Book.Price;
                var author = db.Authors.Find(model.SelectedAuthor);
                if (author == null)
                {
                    model = new AddAuthorToBookModel()
                    {
                        Book = new Book(),

LibraryWebApp/Controllers/GenresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LibraryWebApp.Models;
using LibraryWebApp.Models.ViewModels;

namespace LibraryWebApp.Controllers
{
    public class GenresController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Genres/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id, string returnUrl)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Genre genre = db.Genres.Find(id);
            if (genre == null)
            {
                return HttpNotFound();
            }

            var model = new GenreDetailsViewModel()
            {
                Genre = genre,
                Books = db.Books.Include(b => b.Genre).Where(b => b.Genre.Id == genre.Id).ToList()
            };

            ViewBag.ReturnUrl = returnUrl;
            return View(model);
        }

        // GET: Genres/Create
        [Authorize(Roles = "Admin, Staff")]
        public ActionResult Create(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        // POST: Genres/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Staff")]
        public ActionResult Create([Bind(Include = "Id,Name,Description")] Genre genre, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                db.Genres.Add(genre);
                db.SaveChanges();
                return RedirectToLocal(returnUrl);
            }

            ViewBag.ReturnUrl = returnUrl;
            return View(genre);
        }

        // GET: Genres/Edit/5
        [Authorize(Roles = "Admin, Staff")]
        public ActionResult Edit(int? id, string returnUrl)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Genre genre = db.Genres.Find(id);
            if (genre == null)
            {
                return HttpNotFound();
            }

            ViewBag.ReturnUrl = returnUrl;
            return View(genre);
        }

        // POST: Genres/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Staff")]
        public ActionResult Edit([Bind(Include = "Id,Name,Description")] Genre genre, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                db.Entry(genre).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToLocal(returnUrl);
            }

            ViewBag.ReturnUrl = returnUrl;
            return View(genre);
        }

        // GET: Genres/Delete/5
        [Authorize(Roles = Roles.Admin)]
        public ActionResult Delete(int? id, string returnUrl)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Genre genre = db.Genres.Find(id);
            if (genre == null)
                return HttpNotFound();

            db.Genres.Remove(genre);
            db.SaveChanges();

            return RedirectToLocal(returnUrl);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }

            return RedirectToAction("Index", "Books");
        }
    }
}

LibraryWebApp/Views/Books/Delete.cshtml
@model LibraryWebApp.Models.Book

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pages)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pages)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CoverURL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CoverURL)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PublishPlace)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PublishPlace)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PublishDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PublishDate)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LibraryWebApp/Views/Books/Details.cshtml
@model LibraryWebApp.Models.ViewModels.BookDetailsViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Hidden("IsAuthenticated", Request.IsAuthenticated)

<div id="container" class="container">

    <div class="row bg-primary text-center">
        <h2>Book Details</h2>
    </div>

    <br />

    @if (Model.Book.Quantity > 0)
    {
        <p id="book-quantity-info">
            <strong><span id="book-quantity">@Model.Book.Quantity</span> editions</strong> of <strong>@Model.Book.Title</strong> found in the catalog.
        </p>
    }
    else
    {
        <p>
            <strong class="text-danger">This book is out of stock</strong>
        </p>
    }

    <div class="row">
        <div class="col-sm-2 col-md-3 col-lg-2">
            <img class="img-responsive" src="@Model.Book.CoverURL" style="height: 280px"/>
        </div>

        <div class="col-sm-5 col-md-6 col-lg-7">
            <h4>@Model.Book.Title</h4>
            <p>@Html.ActionLink(Model.Book.Genre.Name, "Details", "Genres", new {id = Model.Book.Genre.Id, ReturnUrl = Html.Encode($"/Books/Details/{Model.Book.Id}") }, new {})</p>
            <p>
                by
                @foreach (var item in Model.Book.Authors)
                {
                    @Html.ActionLink(item.Name, "Details", "Authors", new { id = item.Id, ReturnUrl = Html.Encode($"/Books/Details/{Model.Book.Id}") }, new { })
                    <span>&nbsp;</span>
                }
            </p>

            <p>Published in <span>@Model.Book.PublishPlace</span></p>
            <p>
                by
                @foreach (var item in Model.Book.Publishers)
                {
                    @Html.ActionLink(item.Name, "Details", "Publishers", new { id = item.Id, ReturnUrl = Html.Encode($"/Books/Details/{Model.Book.Id}") }, new { })
                    <span>&nbsp;</span>
                }
            </p>

            <h4>The physical object:</h4>
            <p>Number of pages: @Model.Book.Pages</p>
            <p>Publish date: @Model.Book.PublishDate.ToShortDateString()</p>

            @if (User.IsInRole("Admin") || User.IsInRole("Staff"))
            {
                @Html.ActionLink("Edit", "Edit", "Books", new { id = Model.Book.Id, ReturnUrl = Html.Encode($"/Books/Details/{Model.Book.Id}") }, new { @class = "btn btn-warning" })
            }
            @if (User.IsInRole("Admin"))
            {
                @Html.ActionLink("Delete", "Delete", "Books", new { id = Model.Book.Id, ReturnUrl = ViewBag.ReturnUrl }, new { @class = "btn btn-danger js-delete" })
            }
        </div>

        <div class="col-sm-5 col-md-3 col-lg-3">
            <div id="nav" style="border: 2px dotted gray;">
                <p class="text-center">
                    <strong>Book price: <span id="book-price">@Model.Book.Price</span></strong>
                </p>
                <p class="text-center">
                    <strong>Like this book?</strong>
                </p>
                <div class="text-center" id="btn">

                    @if (Model.Book.Quantity > 0)
                    {
                        <button type="button" class="btn btn-info js-add-to-cart">Add to cart</button>
                    }
                    else
                    {
                        <button type="button" class="btn btn-info " title="Out of stock" disabled>Add to cart</button>
                    }
                </div>
                <br />

                <div class="text-center">
                    <button type="button" class="btn btn-info review-button">Leave a review</button>
                </div>

                <br />

                <div class="text-center">
                    @if (ViewBag.ReturnUrl == null)
                    {
                        @Html.ActionLink("Back to list", "Index", "Books", new {}, new { @class = "btn btn-primary" })
                    }
                    else
                    {
                        <a href="@ViewBag.ReturnUrl" class = "btn btn-primary">Back to list</a>
                    }
                </div>

                <hr />

                <p class="text-center">
                    <strong>Share this book:</strong>
                </p>

                <div id="social" class="text-center">
                    <a href="http://www.facebook.com/">
                        <img src="/images/facebook.png">
                    </a>

                    <a href="http://www.twitter.com/">
                        <img src="/images/twitter.png">
                    </a>
                </div>
            </div>
        </div>
    </div>

    <br /><br />

    @if (Model.BooksByGenre.Count > 0)
    {
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
                <h4 style="color: firebrick">
                    You might also want to read the following books from @Model.Book.Genre.Name genre:
                </h4>
            </div>
        </div>

        <div id="genreCarousel" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                @for (int i = 0; i < Model.BooksByGenre.Count; ++i)
                {
                    if (i == 0)
                    {
                        <li data-target="#genreCarousel" data-slide-to="@i" class="active"></li>
                    }
                    else
                    {
                        <li data-target="#genreCarousel" data-slide-to="@i"></li>
                    }
                }
            </ol>

            <div class="carousel-inner" role="listbox" style="background-color: gray">
                @for (int i = 0; i < Model.BooksByGenre.Count; ++i)
                {
                    if (i == 0)
                    {
                        <div class="item active">
                            <a href="/Books/Details/@Model.BooksByGenre[i].Id?ReturnUrl=@(Html.Encode($"/Books/Details/{Model.Book.Id}"))">
                                <img src="@Model.BooksByGenre[i].CoverURL" class="img-responsive img-thumbnail center-block" style="height: 280px" />
                            </a>
                        </div>
                    }
                    else
                    {
                        <div class="item">
                            <a href="/Books/Details/@Model.BooksByGenre[i].Id?ReturnUrl=@(Html.Encode($"/Books/Details/{Model.Book.Id}"))">
                                <img src="@Model.BooksByGenre[i].CoverURL" class="img-responsive img-thumbnail center-block" style="height: 280px" />
                            </a>
                        </div>
                    }
                }

            </div>
            <a class="left carousel-control" href="#genreCarousel" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#genreCarousel" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
        <br />
    }

    @if (Model.ReviewsForBook.Count > 0)
    {
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
                <h4 style="color: firebrick">Reviews </h4>
            </div>
        </div>

        foreach (var user in Model.ReviewsForBook)
        {
            <div class="media">
                <div class="media-left">
                    <img src="~/images/icon.jpg" style="width: 60px" />
                </div>
                <div class="media-body">
                    <p class="media-heading"><strong>@user.ReviewerUsername</strong> on <strong>@user.ReviewDate</strong></p>
                    <p>@user.ReviewMessage</p>
                </div>
            </div>

            <hr />
        }
    }
    else
    {
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12">
                <h4 class="text-danger alert-danger">
                    No reviews for this book! If you have thoughts about this book, please <a class="review-link" href="#">leave a review</a>.
                </h4>
            </div>
        </div>
    }

</div>

<div id="dialog-review">
    <label for="review">Your review:</label>
    <textarea id="review" class="form-control" placeholder="Write something for this book..." rows="10"></textarea>
</div>

<div id="dialog-delete">
    <p class="alert alert-danger text-danger">
        <span class="glyphicon glyphicon-alert"></span>
        <span>Are you sure you want to delete this item?</span>
    </p>
</div>

@section styles
{
    <link rel="stylesheet" type="text/css" href="@Href("~/Content/jquery-ui.css")" />
    <link rel="stylesheet" type="text/css" href="@Href("~/Content/BookDetailsCss.css")" />
}

@section scripts
{
    <script type="text/javascript" src="@Href("~/Scripts/jquery-ui.js")"></script>

    <script type="text/javascript">
        var button;
        var userId = "@User.Identity.Name";
        var bookCount = @Model.Book.Quantity;
        var bookId = @Model.Book.Id;
        var booksByGenreCount = @Model.BooksByGenre.Count;

        $(document).ready(function() {
            var price = $("#book-price").text();
            $("#book-price").text(new Intl.NumberFormat('en-US', { style: "currency", currency: "USD" }).format(price));

            $(".js-add-to-cart").on("click",
                function() {
                    if ($("#IsAuthenticated").attr("value") === "False") {
                        document.location = "/Account/Login?ReturnUrl=%2FBooks/Details/" + bookId;
                        return;
                    }

                    $.post("/ShoppingCart/AddToCart",
                        { "id": bookId },
                        function(response) {
                            console.log(response);
                            $("#cart-items-count").text(response.CartCount);
                            $(".message").text("Go to checkout");
                        });

                    bookCount--;

                    $("#book-quantity").text(bookCount);

                    if (bookCount === 0) {
                        $("#book-quantity-info").text('<strong class="text-danger">This book is out of stock</strong>');
                        $(".js-add-to-cart").prop("disabled", true);
                        $(".js-add-to-cart").prop("title", "Out of stock");
                    }
                });

            if (booksByGenreCount !== 0) {
                $('.carousel').carousel({
                    animation: 5000,
                    pause: "hover",
                    auto: 10,
                    scroll: 1,
                    visible: 3,
                    wrap: "circular"
                });
            }

            var dialog = $("#dialog-review").dialog({
                title: "Leave a review",
                resizable: false,
                draggable: false,
                autoOpen: false,
                height: 400,
                width: 350,
                modal: true,
                buttons: {
                    "Submit": function() {
                        var reviewMessage = $("#review").val();

                        if (reviewMessage !== "")
                            $.post("/Books/LeaveReview",
                                {
                                    BookID: bookId,
                                    ReviewerUsername: userId,
                                    ReviewMessage: reviewMessage,
                                    ReviewDate: Date.now()
                                },
                                function(response) {
                                    if (response.Code === "200")
                                        location.reload();
                                    else
                                        alert(response.Message);
                                });
                        else
                            alert("Please provide review message!");
                    },
                    "Cancel": function() {
                        $(this).dialog("close");
                    }
                }
            });

            $(".review-button, .review-link").click(function (event) {
                event.preventDefault();
                if ($("#IsAuthenticated").attr("value") === "False") {
                    document.location = "/Account/Login?ReturnUrl=%2FBooks/Details/" + bookId;
                    return;
                }
                dialog.dialog("open");
            });

            var dialogDelete = $("#dialog-delete").dialog({
                resizable: false,
                draggable: false,
                autoOpen: false,
                width: 400,
                modal: true,
                title: "Delete confirmation",
                buttons: {
                    Yes: function() {
                        var url = button.attr("href");
                        window.location = url;
                        dialogDelete.dialog("close");
                    },
                    No: function() {
                        dialogDelete.dialog("close");
                    }
                }
            });

            $("body").on("click", "a.js-delete",
                function(event) {
                    event.preventDefault();
                    button = $(this);
                    dialogDelete.dialog("open");
                });
        });
    </script>
}