LibraryWebApp/Models/ViewModels/ShippingAndPaymentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LibraryWebApp.Models.ViewModels
{
    public class ShippingAndPaymentViewModel
    {
        public Order Order { get; set; }
        public CreditCard CreditCard { get; set; }
    }
}

LibraryWebApp/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.WebPages;
using LibraryWebApp.Models;
using LibraryWebApp.Models.ViewModels;
using PagedList;
using LibraryWebApp.Models.Dto;

namespace LibraryWebApp.Controllers
{
    public class BooksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        
        // GET: Books
        [AllowAnonymous]
        public ActionResult Index(int? page, string orderBy)
        {
            var pageNumber = page ?? 1;
            var pageSize = 16;

            var books = db.Books.Include(m => m.Authors);

            IOrderedQueryable<Book> model;
            switch (orderBy)
            {
                case "price-asc":
                    model = books.OrderBy(b => b.Price);
                    break;
                case "price-desc":
                    model = books.OrderByDescending(b => b.Price);
                    break;
                case "publish-asc":
                    model = books.OrderBy(b => b.PublishDate);
                    break;
                case "publish-desc":
                    model = books.OrderByDescending(b => b.PublishDate);
                    break;
                case "title-asc":
                    model = books.OrderBy(b => b.Title);
                    break;
                case "title-desc":
                    model = books.OrderByDescending(b => b.Title);
                    break;
                case "quantity-asc":
                    model = books.OrderBy(b => b.Quantity);
                    break;
                case "quantity-desc":
                    model = books.OrderByDescending(b => b.Quantity);
                    break;
                default:
                    model = books.OrderBy(b => b.Title);
                    break;
            }

            ViewBag.UserRole = User.IsInRole(Roles.Admin) ? "Admin" :
                User.IsInRole(Roles.Staff) ? "Staff" :
                User.IsInRole(Roles.Member) ? "Member" :
                User.IsInRole(Roles.User) ? "User" : "";

            ViewBag.OrderBy = orderBy;

            return View(model.ToPagedList(pageNumber, pageSize));
        }
        
        // GET: Books/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id, string returnUrl)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Book book = db.Books.Include(b => b.Genre).FirstOrDefault(b => b.Id == id);

            if (book == null)
            {
                return HttpNotFound();
            }

            var booksByGenre = db.Books.Include(b => b.Genre).Where(b => b.Genre.Name == book.Genre.Name).ToList();
            booksByGenre.Remove(book);

            var reviewsForBook = book.Reviews.OrderByDescending(item => item.ReviewDate).ToList();

            var model = new BookDetailsViewModel()
            {
                Book = book,
                BooksByGenre = booksByGenre,
                ReviewsForBook = reviewsForBook
            };

            ViewBag.ReturnUrl = returnUrl;
            return View(model);
        }

        // GET: Books/Create
        [Authorize(Roles = "Admin, Staff")]
        public ActionResult Create(string returnUrl)
        {
            var model = new AddAuthorToBookModel()
            {
                Book = new Book(),
                Authors = (db.Authors.ToList()),
                SelectedAuthor = -1,
                Publishers = (db.Publishers.ToList()),
                SelectedPublisher = -1,
                Genres = (db.Genres.ToList()),
                SelectedGenre = -1
            };

            ViewBag.ReturnUrl = returnUrl;
            return View(model);
        }

        // POST: Books/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Staff")]
        public ActionResult Create(AddAuthorToBookModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                var book = new Book()
                {
                    Title = model.Book.Title,
                    Pages = model.Book.Pages,
                    Quantity = model.Book.Quantity,
                    CoverURL = model.Book.CoverURL,
                    PublishPlace = model.Book.PublishPlace,
                    PublishDate = model.Book.PublishDate,
                    Price = model.Book.Price,
                };
                var author = db.Authors.Find(model.SelectedAuthor);
                if (author == null)
                {
                    model = new AddAuthorToBookModel()
                    {
                        Book = new Book(),
                        Authors = (db.Authors.ToList()),
                        SelectedAuthor = -1,
                        Publishers = (db.Publishers.ToList()),
                        SelectedPublisher = -1,
                        Genres = (db.Genres.ToList()),
                        SelectedGenre = -1
                    };

                    ViewBag.ReturnUrl = returnUrl;
                    ViewBag.ErrorAuthor = "Author does not exists!";
                    return View(model);
                }
                book.Authors.Add(db.Authors.Find(model.SelectedAuthor));

                var publisher = db.Publishers.Find(model.SelectedPublisher);
                if (publisher == null)
                {
                    model = new AddAuthorToBookModel()
                    {
                        Book = new Book(),
                        Authors = (db.Authors.ToList()),
                        SelectedAuthor = -1,
                        Publishers = (db.Publishers.ToList()),
                        SelectedPublisher = -1,
                        Genres = (db.Genres.ToList()),
                        SelectedGenre = -1
                    };

                    ViewBag.ReturnUrl = returnUrl;
                    ViewBag.ErrorPublisher = "Publisher does not exists!";
                    return View(model);
                }
                book.Publishers.Add(db.Publishers.Find(model.SelectedPublisher));

                var genre = db.Genres.Find(model.SelectedGenre);
                if (genre == null)
                {
                    model = new AddAuthorToBookModel()
                    {
                        Book = new Book(),
                        Authors = (db.Authors.ToList()),
                        SelectedAuthor = -1,
                        Publishers = (db.Publishers.ToList()),
                        SelectedPublisher = -1,
                        Genres = (db.Genres.ToList()),
                        SelectedGenre = -1
                    };

                    ViewBag.ReturnUrl = returnUrl;
                    ViewBag.ErrorGenre = "Genre does not exists!";
                    return View(model);
                }
                book.Genre = genre;

                db.Books.Add(book);
                db.SaveChanges();

                return RedirectToLocal(returnUrl);
            }

            model = new AddAuthorToBookModel()
            {
                Book = new Book(),
                Authors = (db.Authors.ToList()),
                SelectedAuthor = -1,
                Publishers = (db.Publishers.ToList()),
                SelectedPublisher = -1,
                Genres = (db.Genres.ToList()),
                SelectedGenre = -1
            };

            ViewBag.ReturnUrl = returnUrl;
            return View(model);
        }
        
        // GET: Books/Edit/5
        [Authorize(Roles = "Admin, Staff")]
        public ActionResult Edit(int? id, string returnUrl)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var book = db.Books.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }

            var model = new AddAuthorToBookModel()
            {
                Book = book,
                Authors = db.Authors.ToList(),
                SelectedAuthor = -1,
                Publishers = db.Publishers.ToList(),
                SelectedPublisher = -1,
                Genres = db.Genres.ToList(),
                SelectedGenre = -1,
            };

            ViewBag.ReturnUrl = returnUrl;
            return View(model);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Staff")]
        public ActionResult Edit(AddAuthorToBookModel model, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                var book = db.Books.Find(model.Book.Id);
                if (book == null)
                    return HttpNotFound();

                book.Title = model.Book.Title;
                book.Pages = model.Book.Pages;
                book.Quantity = model.Book.Quantity;
                book.CoverURL = model.Book.CoverURL;
                book.PublishPlace = model.Book.PublishPlace;
                book.PublishDate = model.Book.PublishDate;
                book.Price = model.Book.Price;
                var author = db.Authors.Find(model.SelectedAuthor);
                if (author == null)
                {
                    model = new AddAuthorToBookModel()
                    {
                        Book = new Book(),

LibraryWebApp/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using LibraryWebApp.Models;
using LibraryWebApp.Models.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace LibraryWebApp.Controllers
{
    [Authorize]
    public class CheckoutController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Checkout
        [HttpGet]
        public ActionResult ShippingAndPayment(string returnUrl)
        {
            var userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            var user = userManager.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);

            if (user == null)
                return HttpNotFound();

            if (!db.Carts.Any(c => c.CartId == user.UserName))
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);

            var model = new ShippingAndPaymentViewModel()
            {
                Order = new Order()
                {
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    Address = user.Address,
                    City = user.City,
                    Country = user.Country,
                    Phone = user.PhoneNumber,
                    Email = user.Email,
                    State = user.Country
                },
                CreditCard = new CreditCard()
            };

            ViewBag.ReturnUrl = returnUrl;
            return View(model);
        }

        [HttpPost]
        public ActionResult ShippingAndPayment(ShippingAndPaymentViewModel model, string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            model.Order.Username = User.Identity.Name;
            model.Order.OrderDate = DateTime.Now;

            var userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            var user = userManager.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);

            if (user == null)
                return HttpNotFound();

            user.FirstName = model.Order.FirstName;
            user.LastName = model.Order.LastName;

            var creditCard = db.CreditCards.Find(model.CreditCard.CardNumber);

            if (creditCard == null ||
                creditCard.CardHolder != model.CreditCard.CardHolder ||
                creditCard.CVV2 != model.CreditCard.CVV2 ||
                creditCard.ExpiryDate != model.CreditCard.ExpiryDate) // credit card doesn't exist
            {
                ModelState.AddModelError("", "Credit card does not exist!");
                return View(model);
            }

            if (creditCard.ExpiryDate < DateTime.Now) // credit card has expired
            {
                ModelState.AddModelError("", "Credit card has expired!");
                return View(model);
            }

            var cart = ShoppingCart.GetCard(this.HttpContext);
            int result = cart.CreateOrder(model.Order, creditCard);

            if (result != -1) // available funds on the credit card
            {
                if (user.Points != 0)
                {
                    var itemsCount = cart.GetCartItems().Sum(x => x.Count);
                    user.Points += (itemsCount * 10);
                    userManager.Update(user);
                }

                return RedirectToAction("Complete", "Checkout", new {id = model.Order.OrderId});
            }

            ModelState.AddModelError("", "Insufficient funds on your balance!");
            return View(model);
        }

        [HttpGet]
        public ActionResult Complete(int? id)
        {
            if (!id.HasValue)
                return HttpNotFound();

            var order = db.Orders.FirstOrDefault(o => o.OrderId == id.Value);

            if (order != null)
            {
                if (order.Username == User.Identity.Name || User.IsInRole("Admin"))
                    return View(id.Value);
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }

            return HttpNotFound();
        }
    }
}

LibraryWebApp/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LibraryWebApp.Models;

namespace LibraryWebApp.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            
            Order order = db.Orders.Include(o => o.OrderDetails).FirstOrDefault(o => o.OrderId == id);
            if (order == null)
                return HttpNotFound();
            
            if (order.Username == User.Identity.Name || User.IsInRole("Admin"))
                return View(order);

            return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LibraryWebApp/Views/Checkout/Complete.cshtml
@model int
@{
    ViewBag.Title = "Complete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="container" class="container">
    <div class="row bg-primary">
        <div class="col-sm-12 text-center">
            <h3>Order placed</h3>
        </div>
    </div>

    <h2>Your order has been placed!</h2>
    <p>
        Thanks for your order! Your order number is:
        <strong>@Html.ActionLink($"{Model}", "Details", "Orders", new {id = Model}, new {})</strong>
    </p>
    <p>How about shopping for some more books in our @Html.ActionLink("library!", "Index", "Books")</p>
</div>

LibraryWebApp/Views/Checkout/ShippingAndPayment.cshtml
@model LibraryWebApp.Models.ViewModels.ShippingAndPaymentViewModel
@{
    ViewBag.Title = "AddressAndPayment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="container" class="container">
    <div class="row bg-primary">
        <div class="col-sm-12 text-center">
            <h3>Shipping Informations</h3>
        </div>
    </div>
    
    @using (Html.BeginForm("ShippingAndPayment", "Checkout", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal" }))
    {
        <small>*If you want to change the personal details you can @Html.ActionLink("edit", "EditDetails", "Manage", new {ReturnUrl = "/Checkout/ShippingAndPayment" }, new {style = "font-weight: bold;"}) your profile!</small>
        <br />
        <div id="shipping">
            @Html.ValidationSummary(true, "", new { @class = "alert alert-danger text-danger" })
            <div class="form-group col-xs-10 col-sm-6 col-md-6 col-lg-4">
                @Html.LabelFor(model => model.Order.FirstName, htmlAttributes: new { @class = "control-label", style = "cursor: pointer;" })
                @Html.EditorFor(model => model.Order.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Order.FirstName, "", new { @class = "text-danger alert-danger small" })
            </div>
            <div class="form-group col-xs-10 col-sm-6 col-md-6 col-lg-4">
                @Html.LabelFor(model => model.Order.LastName, htmlAttributes: new { @class = "control-label", style = "cursor: pointer;" })
                @Html.EditorFor(model => model.Order.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Order.LastName, "", new { @class = "text-danger alert-danger small" })

            </div>
            <div class="clearfix"></div>
            <div class="form-group col-xs-10 col-sm-6 col-md-6 col-lg-4">
                @Html.LabelFor(model => model.Order.Email, htmlAttributes: new { @class = "control-label", style = "cursor: pointer;" })
                @Html.EditorFor(model => model.Order.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Order.Email, "", new { @class = "text-danger alert-danger small" })

            </div>
            <div class="form-group col-xs-10 col-sm-6 col-md-6 col-lg-4">
                @Html.LabelFor(model => model.Order.Phone, htmlAttributes: new { @class = "control-label", style = "cursor: pointer;" })
                @Html.EditorFor(model => model.Order.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Order.Phone, "", new { @class = "text-danger alert-danger small" })
            </div>
            <div class="clearfix"></div>
            <div class="form-group col-xs-10 col-sm-6 col-md-6 col-lg-4">
                @Html.LabelFor(model => model.Order.Address, htmlAttributes: new { @class = "control-label", style = "cursor: pointer;" })
                @Html.EditorFor(model => model.Order.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Order.Address, "", new { @class = "text-danger alert-danger small" })
            </div>
            <div class="form-group col-xs-10 col-sm-6 col-md-6 col-lg-4">
                @Html.LabelFor(model => model.Order.PostalCode, htmlAttributes: new { @class = "control-label", style = "cursor: pointer;" })
                @Html.EditorFor(model => model.Order.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Order.PostalCode, "", new { @class = "text-danger alert-danger small" })
            </div>
            <div class="clearfix"></div>
            <div class="form-group col-xs-10 col-sm-6 col-md-6 col-lg-4">
                @Html.LabelFor(model => model.Order.City, htmlAttributes: new { @class = "control-label", style = "cursor: pointer;" })
                @Html.EditorFor(model => model.Order.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Order.City, "", new { @class = "text-danger alert-danger small" })
            </div>
            <div class="form-group col-xs-10 col-sm-6 col-md-6 col-lg-4">
                @Html.LabelFor(model => model.Order.Country, htmlAttributes: new { @class = "control-label", style = "cursor: pointer;" })
                @Html.EditorFor(model => model.Order.Country, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Order.Country, "", new { @class = "text-danger alert-danger small" })
            </div>
            <div class="clearfix"></div>
            <div class="form-group col-xs-10 col-sm-6 col-md-6 col-lg-4">
                @Html.LabelFor(model => model.Order.State, htmlAttributes: new { @class = "control-label", style = "cursor: pointer;" })
                @Html.EditorFor(model => model.Order.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Order.State, "", new { @class = "text-danger alert-danger small" })
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row bg-primary">
            <div class="col-sm-12 text-center">
                <h3>Payment Informations</h3>
            </div>
        </div>
        <div id="payment">
            <div class="form-group col-xs-10 col-sm-6 col-md-6 col-lg-4">
                @Html.LabelFor(model => model.CreditCard.CardHolder, htmlAttributes: new { @class = "control-label", style = "cursor: pointer;" })
                @Html.EditorFor(model => model.CreditCard.CardHolder, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreditCard.CardHolder, "", new { @class = "text-danger alert-danger small" })
            </div>
            <div class="form-group col-xs-10 col-sm-6 col-md-6 col-lg-4">
                @Html.LabelFor(model => model.CreditCard.CardNumber, htmlAttributes: new { @class = "control-label", style = "cursor: pointer;" })
                @Html.EditorFor(model => model.CreditCard.CardNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreditCard.CardNumber, "", new { @class = "text-danger alert-danger small" })
            </div>
            <div class="clearfix"></div>
            <div class="form-group col-xs-10 col-sm-6 col-md-6 col-lg-4">
                @Html.LabelFor(model => model.CreditCard.ExpiryDate, htmlAttributes: new { @class = "control-label", style = "cursor: pointer;" })
                @Html.TextBox("CreditCard.ExpiryDate", $"{DateTime.Now:yyyy}-{DateTime.Now:MM}", new { @class = "form-control", type = "month", id = "CreditCard_ExpiryDate" })
                @Html.ValidationMessageFor(model => model.CreditCard.ExpiryDate, "", new { @class = "text-danger alert-danger small" })
            </div>
            <div class="form-group col-xs-10 col-sm-6 col-md-6 col-lg-4">
                @Html.LabelFor(model => model.CreditCard.CVV2, htmlAttributes: new { @class = "control-label", style = "cursor: pointer;" })
                @Html.EditorFor(model => model.CreditCard.CVV2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreditCard.CVV2, "", new { @class = "text-danger alert-danger small" })
            </div>
            <div class="clearfix"></div>
            <div class="form-group col-xs-10 col-sm-4 col-md-4 col-lg-4">
                <input type="submit" class="btn btn-primary" value="Place order" />
                @if (ViewBag.ReturnUrl != null)
                {
                    <a href="@ViewBag.ReturnUrl" class="btn btn-default">Go back</a>
                }
                else
                {
                    <a href="/ShoppingCart" class="btn btn-default">Go back</a>
                }
            </div>
        </div>
        <div class="clearfix"></div>
    }
</div>

@section styles
{
    <style>
        .form-group .control-label:after {
            content: "*";
            font-size: 16px;
            color: red;
        }
    </style>
}

@section scripts {
    <script type="text/javascript">
        $(document).ready(function() {
            $("#shipping input[type=text], #shipping input[type=email], #shipping input[type=tel]").each(function() {
                var valMsg = $(this).siblings("span[data-valmsg-for]").text();
                if ($(this).attr("value") !== "" && valMsg === "") {
                    $(this).attr({
                        "title": "We got this from your profile info!",
                        "readonly": "true"
                    });
                }
            });

            $("#CreditCard_CardNumber").on("keydown",
                function(event) {
                    if ((event.keyCode >= 48 && event.keyCode <= 57) || (event.keyCode >= 96 && event.keyCode <= 105)) {
                        var text = $(this).val().split(' ').join('');
                        var length = text.length;
                        if (length !== 0 && length % 4 === 0) {
                            $(this).val($(this).val() + " ");
                        }
                    }
                });

            $("input[type=submit]").click(function() {
                $("#CreditCard_CardNumber").val($("#CreditCard_CardNumber").val().split(' ').join(''));
            });

            var validationSummary =
                $("#shipping > div.validation-summary-errors.alert.alert-danger.text-danger > ul > li");
            if (validationSummary.text() === "") {
                validationSummary.parents("div").removeClass("alert");
            }
        });
    </script>
}